version: '3.1'

services:

  db:
    image: postgres:14
    container_name: nlpf-database
    environment:
      POSTGRES_USER: jobboard
      POSTGRES_PASSWORD: jobboard
      POSTGRES_DB: jobboard
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - nlpf_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  s3:
    image: quay.io/minio/minio:latest
    container_name: nlpf-s3
    environment:
      - MINIO_ROOT_USER=jobboard
      - MINIO_ROOT_PASSWORD=jobboard
    volumes:
      - nlpf_s3_data:/data
    ports:
      - 9000:9000
      - 9090:9090
    command: server /data --console-address ":9090"

  s3_init:
    image: quay.io/minio/mc:latest
    container_name: nlpf-s3-init-buckets
    depends_on:
      - s3
    entrypoint: [ "" ]
    command:
      - sh
      - -c
      - |
        sleep 2
        mc alias set myminio http://s3:9000 jobboard jobboard
        mc mb myminio/candidate-images --ignore-existing
        mc anonymous set download myminio/candidate-images
        mc mb myminio/company-images --ignore-existing
        mc anonymous set download myminio/company-images

volumes:
  nlpf_postgres_data:
  nlpf_s3_data:
