version: '3.1'

services:

  db:
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_USER: jobboard
      POSTGRES_PASSWORD: jobboard
      POSTGRES_DB: jobboard
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
